os:
  - linux
  - osx
language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
branches:
  only:
      - master
env:
  global:
    secure: hPdc6DGdyUHyEMDxLPBNl6iU3545KAuwwIrrbA7aud78f5zvIGeRLC3kGqdUb7yCqtlsGncG/YPvl2VmgByVmctF23I9eUp6KCL44AG4XeGgxSEqPUli9DNw2NrWymsVZCKc2njXP0x7ojl4UJrtCcJT8neEbsBGMqfsxIU9DyqAMScbL42wW/d8Tc10jVDQ7XJ4l6AdvD056KqXvdSqmMpINX/909Wh6i04zxFa4PPKm9QNUzJKAUrZrsZraNVqJC91Vh2v5+GkVnv5KXPk9WTYWyB1cx6tgUsTbfCu28MR1uz5l6Qe11dOCwT0iQL07Z+T+E13msTEyNhcng5YyhPK191vF6vwu2NnylqccCq+RX2avGtzAped62zNGahGg9+kmDyD+vMvtNcm7iw+pOFpyx3h+OuScsZioFm6lB6JfZU47Uo9u5OZWlJeVFvExvJBQMAGLFnwRLC2ZzwjXmxbCRrAm1P3sRnRJgl2TSN5mPCIh4TqZR5FwvhZ9HJWJW0SJp/NEvq77BGzsxYPbarqx5M9XvCaDqxtFieyO/867Zn/Mqc89MqvwBeTNjjLPP2jndzwwC58z9SDBbQprAyFisiFhrOzDSpqis8LtmIkAta1+cRN7kkU0IN/iB8k0SbBi6sTlzIyX7bOsrY5QtD7cCpzGZRKH0APMbZ3QIY=
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/deploy_gh-pages.sh | bash

